### PR TITLE
Support escape code sequences. 

### PR DESCRIPTION
**Pull request by owensd**
This is a fix for issue #27.

Note: This doesn't add support for unicode literals. If we want that, we'll need to do more work.

### CODE REVIEW

**Comment by drewcrawford** [comment]
Okay, when I filed that bug it was somewhat poorly thought out :-)

We have a couple escape mechanisms that are layered here:
1.  atpkg / the one introduced here
2.  atbuild [variable expansion](http://anarchytools.org/docs/variable.html).
3.  shell escapes

So for example, here's a fixture I think we still want to work:

```
(package
  :name "plugin"

  :tasks {
    :a {:tool "nop" }
    :default {
      :tool "echo.attool"
      :userpath "\${ATBUILD_USER_PATH}"
)
```

Before this patch, the logic looks like this:
1.  `${ATBUILD_USER_PATH}` is the syntax for an atbuild variable expansion
2.  However, there's not one with that name.  This would normally produce an error.
3.  So we escape [atbuild variable expansion](http://anarchytools.org/docs/variable.html) via `\${ATBUILD_USER_PATH}`.  Now it escapes/evaluates to the literal `${ATBUILD_USER_PATH}`, bash will expand this as an environment variable.

After this patch:
1.  atpkg interprets `"\${ATBUILD_USER_PATH}` as an _atpkg_ escape
2.  Since there is no valid atpkg escape sequence starting with `\$`, parse fails.

IMO one solution is to have atpkg pass-through `\$` as `\$`.  This is not an escape code atpkg will likely ever need, and it allows existing atbuild variable expansion escapes to continue to work.  I don't believe the atbuild expansion engine will need escapes beyond that one, although I could be wrong.

Another solution would be to require `\\${SHELL_VARIABLE}` but that is ugly and we would need to support both syntaxes for at least one release as a migration path.

**Comment by owensd** [comment]
Ok. I'll add that to the next iteration.

**Comment by owensd** [comment]
Alrighty, I think I added the thing you were looking for.

**Comment by drewcrawford** [comment]
LGTM, thanks!

**Pull request merged**
